import { Shadows } from '@mui/material';

export const PRIMARY_SHADOW = 'rgba(0, 0, 0, 0.1) 0px 0px 12px';

export const shadows: Shadows = [
  'none',
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
  PRIMARY_SHADOW,
];
